### ISSUE TITLE
active depot via aur

### ISSUE THREAD

**Issue by papajoker** [tuxnvape/AMAR#1]
idée
Il ne serait pas plus simple d'activer/désactiver le dépôt simplement en installant/désinstallant le paquet ?
Cela évite d'avoir à garder des dépendances installées

pkgbuild
```
pkgname=amar-install
pkgver=1
pkgrel=1
pkgdesc="Install AMAR repository"
arch=('x86_64')
license=('GPL3')
url="https://www.tuxnvape.fr/"
install=amar.install
```
amar.install
```
post_install() {
  sed -i '/amar/Id' /etc/pacman.conf 
  cat << EOF >> /etc/pacman.conf
  
[AMAR]
SigLevel=Never #amar
Server=https://amar.roro-home.fr/AMAR/x86_64/
EOF
}

post_upgrade() {
  post_install
}

post_remove() {
  sed -i '/amar/Id' /etc/pacman.conf 
}
```

**Comment by tuxnvape** [comment]
C'est une bonne, je vais y réfléchir avec les membres de TuxNvape. C'est vrai que moins de dépendances à installer pour les utilisateurs, c'est gagner en facilité de mise en place d'utilisation.
