### ISSUE TITLE
Erreur de lancement avec la Manjaro Mate officielle

### ISSUE THREAD

**Issue by seigneurfuo** [tuxnvape/AMAR#2]
Bonjour. Je rapporte ici en temps que "problème" mais cette publication est surtout un aide-mémoire pour les futures personnes qui rencontreraient également ce soucis:

Sur la Manjaro Mate Officielle 17.1.9, on obtient l'erreur suivante:

Message d'erreur:
```
$ sudo /usr/bin/python /usr/bin/amar.py
Traceback (most recent call last):
  File "/usr/bin/amar.py", line 82, in <module>
    win = Tk()
  File "/usr/lib/python3.6/tkinter/__init__.py", line 2020, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: unknown color name "BACKGROUND"
```

En recherchant sur le web (https://dev.solus-project.com/T3830), on peut trouver une ligne de commande afin de corriger le tout:

```
xrdb -all -query|sed -e 's#[A-Z_]*BACKGROUND# gray90#' \
-e 's#[A-Z_]*FOREGROUND# Black#' \
-e 's#[A-Z_]*HIGHLIGHT# White#' \
-e 's#[A-Z_]*LOWLIGHT# Black#'|xrdb -merge
```
Et le script se lance enfin sans aucun problèmes.

Une simple erreur de configuration sur la Manjaro Mate Officielle ?

**Comment by tuxnvape** [comment]
Pour résoudre ce problème, je pense modifier le scripte amar.py de ce sorte qu'il exécute la commande que vous m'avez donner avant d'afficher l'interface utilisateur.

**Comment by tuxnvape** [comment]
Issue fixed, bug closed
